### ISSUE TITLE
`revertedWith` not matching errors

### ISSUE THREAD

**Issue by NoahZinsmeister** [EthWorks/Waffle#174]
as of `2.1.1`, and still in `2.2.0`, tests of the form `.to.be.revertedWith('...')` aren't working properly (they don't catch the actual string from `require`s.

`AssertionError: Expected transaction to be reverted with ..., but other exception was thrown: execution error: revert`

**Comment by marekkirejczyk** [comment]
This is super annoying. Happens due to update in ethers, which now does estimate gas before sending. Ganache will not return proper errors when estimating.
No idea how to solve it yet. 
Workaround: pass gasLimit to a function call.

See example [here](https://github.com/UniversalLogin/UniversalLoginSDK/commit/e3aba9da890fe1e824bff841ff316450712de651.)

**Comment by NoahZinsmeister** [comment]
this indeed addresses some of the out of gas errors i was getting, but the require error string is still not getting matched even when the tx has enough gas

**Comment by NoahZinsmeister** [comment]
going to open another issue re. gas estimation failing
