### ISSUE TITLE
deployContract TypeChain support

### ISSUE THREAD

**Issue by sz-piotr** [EthWorks/Waffle#188]
We have this function `deployContract`. The current signature is:
```ts
async function deployContract(
  wallet: Wallet,
  contractJSON: ContractJSON,
  args: any[] = [],
  overrideOptions: providers.TransactionRequest = {}
): Promise<Contract>
```

This however leads to requiring a cast to the TypeChain contract class after deploying. E.g.
```ts
const contract = (await deployContract(wallet, contractJSON, [])) as MyTypedContract
```

One idea is to change the signature as follows:
```ts
async function deployContract<T extends Contract>(
  wallet: Wallet,
  contractJSON: ContractJSON,
  args: any[] = [],
  overrideOptions: providers.TransactionRequest = {}
): Promise<T>
```

Then the deploy is easier:
```ts
const contract = await deployContract<MyTypedContract>(wallet, contractJSON, [])
```

I am however not a fan of this solution, because it does not guarantee correctness of the code on the type level. It is trivial to incorrectly assign the generic type parameter if we have multiple contracts, which leads to further errors.

**Comment by sz-piotr** [comment]
@alcuadrado Let me know your comments

**Comment by alcuadrado** [comment]
> I am however not a fan of this solution, because it does not guarantee correctness of the code on the type level. It is trivial to incorrectly assign the generic type parameter if we have multiple contracts, which leads to further errors.

I agree with this. I'm not sure what a better solution would be though.

Any thoughts on this, @rhlsthrm and krzkaczor?

**Comment by sz-piotr** [comment]
@krzkaczor

**Comment by rhlsthrm** [comment]
I agree with the concerns, I would rather cast the contract after deploying.

**Comment by krzkaczor** [comment]
> I am however not a fan of this solution, because it does not guarantee correctness of the code on the type level. It is trivial to incorrectly assign the generic type parameter if we have multiple contracts, which leads to further errors.

Nor does casting ;) IMO we should follow "best-effort" strategy here. 

We solved a very similar problem with Truffle in the way that `deploy` function had multiple overrides to differentiate between deployed contracts `deploy("Weth"): Promise<WethContract>` (more or less). With this approach, we could easily have typed constructors as well. 

This case is slightly more complicated since `deployContract` takes JSON describing contract, which would be hard to override. 

I am a huge fan of maximum possible correctness so I would go with what @sz-piotr suggested but with few changes: 

1. Type argument should not be a Contract but rather factory? This way you can type args properly.
2. You might want to consider adding `any` as a default T value for users that do not use TypeChain.

Something like this?

```typescript
async function deployContract<T extends ContractFactory = any>(
  wallet: Wallet,
  contractJSON: ContractJSON,
  args: Parameters<T['deploy']>,
  overrideOptions: providers.TransactionRequest = {}
): Promise<T>
```

It's totally possible for the user to pass `contractJSON` with wrong type argument but hopefully, making them pass constructor parameters will help them realize that something is not right. Also, it's quite an easy error to find in runtime so I wouldn't worry too much about it.

**Comment by minton1** [comment]
Hey! Im curious about progress here or other ways to call deployContract that is more strongly typed. In particular, is this possible, or should it be possible? 

```
const AuctionsContractFactory = await ethers.getContractFactory("Auctions");
let auctions = (await AuctionsContractFactory.deploy(a, b.address)) as unknown as Auctions;
await auctions.deployed();
```
to 
```
import { AuctionsFactory } from "../typechain/AuctionsFactory";    
...
let auctions = await AuctionsFactory.deploy(a.address, b.address);
await auctions.deployed();
```

Looking in typechain/AuctionsFactory.ts there is a deploy function right there that returns the proper type ("Auctions" instead of "Contract")

**Comment by aliskhanoff** [comment]
What is ContractJson? Is ContractABI?
